### ISSUE TITLE
Rubric Assesment

### ISSUE THREAD

**Issue by martendebruijn** [MarjoleinAardewijn/web-app-from-scratch-1920#15]
> Je kan structuur aanbrengen in je code door patterns toe te passen. Je kan de keuze voor de gekozen patterns beargumenteren

Goede code structuur, fijne tabjes wat je code goed leesbaar maakt. Ook zet je veel comments bij je code, wat voor een lezer van buiten-af het makkelijk maakt om je code te lezen.

> Code is correct gescoped en opgedeeld in modules die overeen komen met het actor diagram.

De code is (nog) niet opgedeeld in modules.

> Je kan data ophalen, manipuleren en dynamisch omzetten naar html elementen mbv templating. Je begrijpt hoe je middels asynchrone code met een externe API kan werken.

Data haal je op via een fetch met promise. De data mag je nog meer manipuleren. Omzetten naar html elementen doe je wel, maar nog niet via templating.

> Je begrijpt hoe je states in je applicaties kan managen en stelt de gebruiker op de hoogte van states waar nodig.

Je maakt gebruik van routing. Je maakt nog geen gebruik van state feedback.

**Comment by MarjoleinAardewijn** [comment]
Code opgedeeld in modules.

**Comment by MarjoleinAardewijn** [comment]
State feedback toegevoegd

**Comment by MarjoleinAardewijn** [comment]
Data gemanipuleerd door een filter erop te zetten.
